package:
    name: nrel-rev
    version: {{ environ.get('GIT_DESCRIBE_TAG','').replace('v', '', 1) }}

source:
    git_url: ../

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
    - NREL-rex>=0.2.58
    - NREL-PySAM>=2.1.4,!=2.2.*
    - packaging
    - plotting
    - plotly
  run:
    - python
    - pip
    - NREL-rex>=0.2.58
    - NREL-PySAM>=2.1.4,!=2.2.*
    - packaging
    - plotting
    - plotly

about:
  home: "https://github.com/NREL/reV"
  license: BSD 3-Clause
  summary: "The Renewable Energy Potential (reV) Model"
  doc_url: "https://nrel.github.io/reV"
  dev_url: "https://github.com/NREL/reV"
