package:
    name: nrel-rev
    version: {{ environ.get('GIT_DESCRIBE_TAG','').replace('v', '', 1) }}

source:
    git_url: ../

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
    - click
    - h5py
    - numpy>=1.16
    - pandas
    - packaging
    - plotting
    - plotly
    - psutil
    - scipy
    - NREL-rex
    - NREL-PySAM>=2.1.4
  run:
    - python
    - pip
    - click
    - h5py
    - {{ pin_compatible('numpy') }}
    - pandas
    - packaging
    - plotting
    - plotly
    - psutil
    - scipy
    - NREL-rex
    - NREL-PySAM>=2.1.4

about:
  home: "https://github.com/NREL/reV"
  license: BSD 3-Clause
  summary: "The Renewable Energy Potential (reV) Model"
  doc_url: "https://nrel.github.io/reV"
  dev_url: "https://github.com/NREL/reV"
